/**
 * Single Source of Truth for Domain Enums in NestSphere ERP.
 * Strictly mirrors backend Prisma schema definitions.
 */

export enum VisitorTypeCategory {
  GUEST = 'GUEST',
  RELATIVE = 'RELATIVE',
  FRIEND = 'FRIEND',
  VENDOR = 'VENDOR',
  COURIER = 'COURIER',
  FOOD_DELIVERY = 'FOOD_DELIVERY',
  CAB_DRIVER = 'CAB_DRIVER',
  SERVICE_ENGINEER = 'SERVICE_ENGINEER',
  TECHNICIAN = 'TECHNICIAN',
  HOUSEKEEPING = 'HOUSEKEEPING',
  GOVERNMENT_OFFICER = 'GOVERNMENT_OFFICER',
  POLICE = 'POLICE',
  FIRE_BRIGADE = 'FIRE_BRIGADE',
  AMBULANCE = 'AMBULANCE',
  OTHER = 'OTHER',
}

export enum VisitorPassStatus {
  PRE_APPROVED = 'PRE_APPROVED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CHECKED_IN = 'CHECKED_IN',
  CHECKED_OUT = 'CHECKED_OUT',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum ComplaintCategory {
  PLUMBING = 'PLUMBING',
  ELECTRICAL = 'ELECTRICAL',
  ELEVATOR = 'ELEVATOR',
  SECURITY = 'SECURITY',
  CLEANLINESS = 'CLEANLINESS',
  NOISE = 'NOISE',
  PARKING = 'PARKING',
  WATER_SUPPLY = 'WATER_SUPPLY',
  CONSTRUCTION = 'CONSTRUCTION',
  OTHER = 'OTHER',
}

export enum ComplaintPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum ComplaintStatus {
  LOGGED = 'LOGGED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
  CANCELLED = 'CANCELLED',
}

export enum MeetingType {
  AGM = 'AGM',
  SGM = 'SGM',
  COMMITTEE = 'COMMITTEE',
  EMERGENCY = 'EMERGENCY',
  VIRTUAL = 'VIRTUAL',
  HYBRID = 'HYBRID',
}

export enum MeetingStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum NoticeCategory {
  GENERAL = 'GENERAL',
  MAINTENANCE = 'MAINTENANCE',
  EVENT = 'EVENT',
  EMERGENCY = 'EMERGENCY',
  ELECTION = 'ELECTION',
  SECURITY = 'SECURITY',
  BILLING = 'BILLING',
}

export enum NoticePriority {
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum ParkingType {
  RESIDENT_COVERED = 'RESIDENT_COVERED',
  RESIDENT_OPEN = 'RESIDENT_OPEN',
  VISITOR_OPEN = 'VISITOR_OPEN',
  TWO_WHEELER = 'TWO_WHEELER',
  EV_CHARGING = 'EV_CHARGING',
  HANDICAPPED = 'HANDICAPPED',
}
